apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/dg-bee/environment-painterember-dev.git
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    dockerRegistryOrg: apps-dev-229310
    envOrganisation: dg-bee
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: dg-bee
    promotionEngine: Prow
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://painterember-lts-0b5d761b-30c1-44f3-8b42-ab339af90306
      classifier: default
    - bucketUrl: gs://painterember-lts-0b5d761b-30c1-44f3-8b42-ab339af90306
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
